### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by codecat** [Bromvlieg/TomatoLib#3]
What about Linux support? Would be cool if this builds via cmake (since you can add glfw as a submodule and use `add_subdirectory` to tell cmake to build glfw as part of the TomatoLib build). This way, programs that use TomatoLib could do exactly the same.

I might give it a shot to make a cmake file and do a pull request, if you want.

**Comment by Bromvlieg** [comment]
The code should be cross platform (that's what I aimed for, might missed some things trough) so should work out, dunno how the cmake stuff works myself so i'd have to take a look at it

**Comment by codecat** [comment]
I have a branch on my fork which currently builds on Linux and Mac, I'll do a pull request when I can confirm it works.

**Comment by codecat** [comment]
See #5
